language: R
sudo: false
cache:
- packages

r_packages:
- logging
- futile.logger
- log4r
- microbenchmark

after_success:
- Rscript -e 'library(devtools);install();test()'
- Rscript -e 'Sys.setenv(NOT_CRAN = "true");covr::codecov()'

before_deploy: Rscript -e 'install.packages("pkgdown", repos="http://mran.microsoft.com/snapshot/2020-09-01/")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(new_process = FALSE)'
  skip_cleanup: true
  on:
    branch: master
