language: R
sudo: false
cache:
- packages

r_packages:
- logging
- futile.logger
- log4r
- microbenchmark

after_success:
- Rscript -e 'library(devtools);install();test()'
- Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'devtools::install_github("r-lib/pkgdown@v1.3.0")'
deploy:
  provider: script
  script: Rscript -e 'library(pkgdown);sessionInfo();deploy_site_github(new_process = FALSE)'
  skip_cleanup: true
  on:
    branch: master
